### ISSUE TITLE
udp6 face creation not working

### ISSUE THREAD

**Issue by yoursunny** [named-data/YaNFD#6] opened 2021-05-25 17:05 UTC
YaNFD version: a4132a8c28c87477e401d4fef74a9a3db979a7c1
nfdc version: 0.7.1-23-g6a699be8

1. Bring up a network interface and assign an IPv6 ULA address:

    ```bash
    sudo ip link set enp94s0 up
    sudo ip addr replace fd54:450f:f5ac:807a::2/64 dev enp94s0
    ```

2. Start YaNFD.
3. Try to create a face:

    ```bash
    nfdc face create udp6://[fd54:450f:f5ac:807a::1]:6363
    ````

Expected: face creation succeeds.
Actual:

* nfdc returns `Error 406 when creating face: Unsupported scheme udp6`
* YaNFD log contains `WARN[3207] [FaceMgmt] Unable to create unicast UDP face with URI udp6://[fd54:450f:f5ac:807a::1]:6363: Unsupported scheme udp6://[fd54:450f:f5ac:807a::1]:6363`

**Comment by eric135** [comment] 2021-05-25 19:49
This is fixed in db48f3f. This was caused by missing square brackets around IPv6 addresses.

**Closed by eric135** 2021-05-25 19:49 UTC
